### ISSUE TITLE
Access to monitoring returns a HTTP Status 403 - Forbidden access message

### ISSUE THREAD

**Issue by enderwig70** [javamelody/liferay-javamelody#4]
I want to secure the context monitoring for the javamelody liferay hook on a liferay 6.1.2-ce-GA3. I've tested it with the 1.53.0 version and added the filter with the parameter "authorized-users" for BASIC authentication, as explained in https://code.google.com/p/javamelody/wiki/ReleaseNotes#1.53.0

When i go tho the url http://hostname:8080/monitoring i receive:

HTTP Status 403 - Forbidden access
type Status report
message Forbidden access
description Access to the specified resource has been forbidden.
Apache Tomcat/7.0.40

It doesn't ask for a username or password and i get no errors in the catalina.out log. It's very similar to https://code.google.com/p/javamelody/issues/detail?id=420

I did something wrong?

**Comment by ranjithchittuluri** [comment]
i am running liferay on 8 nodes. and using ADFS for login , my login is configured at apache level, how can i login to individual node ,  is there any way i can make it public  i am running this for a performance monitoring on PT environment , please suggsst 
my liferay node is 
http://123.34.45.8:8080/
apache
127.34.45.5
domain (login integrated here with adfs at domain name landing will be done on domain name)
myptenvronmrnt.com 
kindly suggest how can i skip login 

Ranjith
