### ISSUE TITLE
Access to monitoring returns a HTTP Status 403 - Forbidden access message when accessed from loadbalancer, and how to identify each nodes

### ISSUE THREAD

**Issue by ranjithchittuluri** [javamelody/liferay-javamelody#8]
i am running liferay on 8 nodes. and using ADFS for login , my login is configured at apache level, how can i login to individual node , is there any way i can make it public i am running this for a performance monitoring on PT environment , please suggsst
my liferay node is
http://123.34.45.8:8080/
apache
127.34.45.5
loadbalancer
domain (login integrated here with adfs at domain name landing will be done on domain name)
myptenvronmrnt.com
kindly suggest how can i skip login

Ranjith

**Comment by evernat** [comment]
If you want to disable the Liferay login needed to access the /monitoring page, I have just added a system property `-Djavamelody.plugin-authentication-disabled=true` to disable it. And you need to download and deploy the new build at:
https://javamelody.ci.cloudbees.com/job/liferay-javamelody/lastSuccessfulBuild/artifact/target/liferay-javamelody-hook-1.65.0.0.war

You can add the following line in tomcat/conf/catalina.properties for example:
```
javamelody.plugin-authentication-disabled=true
```

To choose an individual Liferay node in a cluster, you can either open http://123.34.45.8:8080/monitoring with the ip of the node directly Or if you have apache as loadbalancer you may have a cookie named ROUTEID in your browser, then using something like Firebug in Firefox, you can edit the ROUTEID cookie to change the number inside.
